### ISSUE TITLE
Meshs dont export.

### ISSUE THREAD

**Issue by coreartz** [errorcodecritical/Adamastor#1]
It dont export any models for me. It also dont give errors. Textures work. I used to wait 5min before closing it. 
Used this command:
node ./adamastor https://sketchfab.com/3d-models/scavenger-cute-creature-9ab26d785b3048f8ae892dbee934f35d

![image](https://user-images.githubusercontent.com/61552558/233974991-7f757c64-12ee-43f6-a7ef-190c40ab4254.png)

**Comment by errorcodecritical** [comment]
Hi @coreartz, I've temporarily fixed the loading issue - do note that this is not a long term solution, since I can't vouch for the consistency of the method I use.

**Comment by coreartz** [comment]
Haay first of thx for the fast respond. It sadly still dont dump any Model for me. Could it be that my Chrome version could be the problem? Or anything else maybe?
![image](https://user-images.githubusercontent.com/61552558/234028779-6dd4c6b8-ec54-467e-bd8a-15baf47fce55.png)

**Comment by errorcodecritical** [comment]
I'm noticing your logs aren't displaying any debug messages. Please confirm you have the cloned the latest version of the repository. Logs should appear as in the image below:

![Screenshot_20230424_173925](https://user-images.githubusercontent.com/80753888/234061725-2222f8fa-9d03-4c7e-8da4-40e85f95ebcb.png)

**Comment by coreartz** [comment]
Okay yeah looks like I downloaded the new versio but open the cmd in the old folder. My fail :D Now it work perfectly fine!
