### ISSUE TITLE
No mesh being downloaded

### ISSUE THREAD

**Issue by ILikeTurtles42** [errorcodecritical/Adamastor#2]
Similar to the last issue that was marked as solved no mesh is downloading. I am getting textures perfectly but the extract_geometry.js never executes and there is no console log. 

I believe the issue is on line 36  let index2 = body.search(/var .=.,.=.\[.\(\d*\)\]\(\),.=.\.getInstanceID\(\);/); //body.indexOf('var r=c,e=t[r(392)](),n=e.getInstanceID();');

I think this text can't be found in the index html, and thus never sets index2 to true which doesn't start extract_geometry.

Do you have any ideas / workarounds to getting the mesh to work?

Thank you again this is really a fantastic script!

**Comment by errorcodecritical** [comment]
Hey @ILikeTurtles42, I apologize for taking so long to get back to you on this. 

It broke as a result of the developers changing where and how the data is stored on their website. I've already gone ahead and added a simple hot-fix to accommodate for these changes, please try it out!

I should really make the code a little more maintainable, at least then it might be easier for anyone willing to contribute to this effort :sweat_smile:
